on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please-bump

jobs:
  release:
    runs-on: macos-latest
    steps:
    - uses: google-github-actions/release-please-action@v3
      id: release-please
      with:
        release-type: simple
        package-name: release-please-action
    - uses: actions/checkout@v3
      if: ${{ !steps.release-please.output.release_created }}
      with:
        ref: ${{ steps.release-please.output.release_pr.headBranchName }}
    - name: bump
      if: ${{ !steps.release-please.output.release_created }}
      run: |
        xcrun agvtool new-marketing-version ${{ steps.release-please.output.version }}
    - name: push
      if: ${{ !release-please.release_created }}
      run: |
        git add .
        git commit -m ":robot: bump version on ${{ steps.release-please.output.version }}"
        git push origin ${{ steps.release-please.output.headBranchName }}
