on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: release-please-action
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.version }}
      body: ${{ steps.release.outputs.body }}
  versionup:
    needs:
      - release-please
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: yanamura/ios-bump-version@v1
      with:
        version: ${{ needs.release-please.outputs.version }}
